# Generated by Django 4.2.2 on 2023-06-21 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.CharField(max_length=200, unique=True, verbose_name='Телеграм')),
                ('role', models.CharField(choices=[('guest', 'Гость'), ('speaker', 'Спикер'), ('organizer', 'Организатор')], default='guest', max_length=10, verbose_name='Спикер или Гость?')),
                ('donation', models.FloatField(default=0, null=True, verbose_name='Сумма доната')),
            ],
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Время начала доклада')),
                ('topic', models.CharField(max_length=200, verbose_name='Тема выступления')),
                ('duration', models.DurationField(verbose_name='Продолжительность доклада')),
                ('is_active_now', models.BooleanField(default=False)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='meetup_bot.member', verbose_name='Спикер')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Ваше имя')),
                ('age', models.IntegerField(verbose_name='Сколько вам лет?')),
                ('company', models.CharField(blank=True, max_length=100, verbose_name='Компания')),
                ('job', models.CharField(blank=True, max_length=100, verbose_name='Ваша должность')),
                ('stack', models.CharField(blank=True, max_length=200, verbose_name='С какими технологиями работаете?')),
                ('hobby', models.CharField(blank=True, max_length=100, verbose_name='Ваше хобби?')),
                ('goal', models.CharField(blank=True, max_length=100, verbose_name='Цель знакомства?')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Регион')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='meetup_bot.member', verbose_name='Спрашивающий')),
            ],
        ),
    ]
