# Generated by Django 4.2.1 on 2023-06-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'verbose_name': 'Донаты', 'verbose_name_plural': 'Донаты'},
        ),
        migrations.AlterModelOptions(
            name='form',
            options={'verbose_name': 'Анкета', 'verbose_name_plural': 'Анкеты'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Участник', 'verbose_name_plural': 'Участники'},
        ),
        migrations.AlterModelOptions(
            name='presentation',
            options={'verbose_name': 'Презентация', 'verbose_name_plural': 'Презентации'},
        ),
        migrations.AlterField(
            model_name='member',
            name='telegram_id',
            field=models.IntegerField(unique=True, verbose_name='telegram_id'),
        ),
        migrations.AlterField(
            model_name='member',
            name='telegram_name',
            field=models.CharField(max_length=200, verbose_name='Телеграм'),
        ),
    ]
