# Generated by Django 4.2.1 on 2023-06-24 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetup_bot', '0003_rename_donation_donat_alter_member_telegram_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donat',
            new_name='Donation',
        ),
    ]
