# Generated by Django 4.2.1 on 2023-06-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup_bot', '0004_rename_donat_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donate_time',
            field=models.DateTimeField(verbose_name='Время доната'),
            preserve_default=False,
        ),
    ]
