# Generated by Django 4.2.1 on 2023-06-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup_bot', '0005_remove_donation_donation_donation_donate_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='donation',
        ),
        migrations.AlterField(
            model_name='donation',
            name='donate_time',
            field=models.DateTimeField(null=True, verbose_name='Время доната'),
        ),
    ]
