# Generated by Django 4.2.1 on 2023-06-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup_bot', '0006_remove_donation_donation_alter_donation_donate_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donation',
            field=models.FloatField(default=0, null=True, verbose_name='Сумма доната'),
        ),
    ]
